# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server

    The version of the OpenAPI document: buildtime:202404131246 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_new_apikey_post200_response import MerchantNewApikeyPost200Response

class TestMerchantNewApikeyPost200Response(unittest.TestCase):
    """MerchantNewApikeyPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantNewApikeyPost200Response:
        """Test MerchantNewApikeyPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantNewApikeyPost200Response`
        """
        model = MerchantNewApikeyPost200Response()
        if include_optional:
            return MerchantNewApikeyPost200Response(
                code = 56,
                data = openapi_client.models._merchant_new_apikey_post_200_response_data._merchant_new_apikey_post_200_response_data(
                    api_key = '', ),
                message = '',
                redirect = '',
                request_id = ''
            )
        else:
            return MerchantNewApikeyPost200Response(
        )
        """

    def testMerchantNewApikeyPost200Response(self):
        """Test MerchantNewApikeyPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
