# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_subscription_admin_note_list_get200_response import MerchantSubscriptionAdminNoteListGet200Response

class TestMerchantSubscriptionAdminNoteListGet200Response(unittest.TestCase):
    """MerchantSubscriptionAdminNoteListGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantSubscriptionAdminNoteListGet200Response:
        """Test MerchantSubscriptionAdminNoteListGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantSubscriptionAdminNoteListGet200Response`
        """
        model = MerchantSubscriptionAdminNoteListGet200Response()
        if include_optional:
            return MerchantSubscriptionAdminNoteListGet200Response(
                code = 56,
                data = openapi_client.models._merchant_subscription_admin_note_list_get_200_response_data._merchant_subscription_admin_note_list_get_200_response_data(
                    note_lists = [
                        openapi_client.models.unibee/api/merchant/subscription/admin_note_ro.unibee.api.merchant.subscription.AdminNoteRo(
                            create_time = 56, 
                            email = '', 
                            first_name = '', 
                            id = 56, 
                            last_name = '', 
                            mobile = '', 
                            note = '', 
                            subscription_id = '', 
                            user_name = '', )
                        ], ),
                message = '',
                redirect = '',
                request_id = ''
            )
        else:
            return MerchantSubscriptionAdminNoteListGet200Response(
        )
        """

    def testMerchantSubscriptionAdminNoteListGet200Response(self):
        """Test MerchantSubscriptionAdminNoteListGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
