# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_bean_detail_invoice_detail import UnibeeApiBeanDetailInvoiceDetail

class TestUnibeeApiBeanDetailInvoiceDetail(unittest.TestCase):
    """UnibeeApiBeanDetailInvoiceDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiBeanDetailInvoiceDetail:
        """Test UnibeeApiBeanDetailInvoiceDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiBeanDetailInvoiceDetail`
        """
        model = UnibeeApiBeanDetailInvoiceDetail()
        if include_optional:
            return UnibeeApiBeanDetailInvoiceDetail(
                crypto_amount = 56,
                crypto_currency = '',
                currency = '',
                data = '',
                day_util_due = 56,
                discount_amount = 56,
                gateway = openapi_client.models.unibee/api/bean/gateway_simplify.unibee.api.bean.GatewaySimplify(
                    country_config = {
                        'key' : True
                        }, 
                    gateway_id = 56, 
                    gateway_logo = '', 
                    gateway_name = '', 
                    gateway_type = 56, ),
                gateway_id = 56,
                gateway_invoice_id = '',
                gateway_invoice_pdf = '',
                gateway_payment_id = '',
                gateway_status = '',
                gateway_user_id = '',
                gmt_create = '',
                gmt_modify = '',
                id = 56,
                invoice_id = '',
                invoice_name = '',
                is_deleted = 56,
                lines = [
                    openapi_client.models.unibee/api/bean/invoice_item_simplify.unibee.api.bean.InvoiceItemSimplify(
                        amount = 56, 
                        amount_excluding_tax = 56, 
                        currency = '', 
                        description = '', 
                        period_end = 56, 
                        period_start = 56, 
                        proration = True, 
                        quantity = 56, 
                        tax = 56, 
                        tax_scale = 56, 
                        unit_amount_excluding_tax = 56, )
                    ],
                link = '',
                merchant = openapi_client.models.unibee/api/bean/merchant_simplify.unibee.api.bean.MerchantSimplify(
                    address = '', 
                    business_num = '', 
                    company_logo = '', 
                    company_name = '', 
                    create_time = 56, 
                    email = '', 
                    home_url = '', 
                    host = '', 
                    id = 56, 
                    idcard = '', 
                    location = '', 
                    name = '', 
                    phone = '', 
                    time_zone = '', 
                    type = 56, 
                    user_id = 56, ),
                merchant_id = 56,
                payment = openapi_client.models.unibee/api/bean/payment_simplify.unibee.api.bean.PaymentSimplify(
                    authorize_reason = '', 
                    authorize_status = 56, 
                    automatic = 56, 
                    balance_amount = 56, 
                    billing_reason = '', 
                    cancel_time = 56, 
                    country_code = '', 
                    create_time = 56, 
                    currency = '', 
                    external_payment_id = '', 
                    failure_reason = '', 
                    gas_payer = '', 
                    gateway_id = 56, 
                    gateway_payment_id = '', 
                    invoice_id = '', 
                    link = '', 
                    merchant_id = 56, 
                    metadata = {
                        'key' : ''
                        }, 
                    paid_time = 56, 
                    payment_amount = 56, 
                    payment_id = '', 
                    refund_amount = 56, 
                    return_url = '', 
                    status = 56, 
                    subscription_id = '', 
                    total_amount = 56, 
                    user_id = 56, ),
                payment_id = '',
                period_end = 56,
                period_start = 56,
                refund = openapi_client.models.unibee/api/bean/refund_simplify.unibee.api.bean.RefundSimplify(
                    country_code = '', 
                    create_time = 56, 
                    currency = '', 
                    external_refund_id = '', 
                    gateway_id = 56, 
                    gateway_refund_id = '', 
                    merchant_id = 56, 
                    metadata = {
                        'key' : ''
                        }, 
                    payment_id = '', 
                    refund_amount = 56, 
                    refund_comment = '', 
                    refund_id = '', 
                    refund_time = 56, 
                    return_url = '', 
                    status = 56, 
                    subscription_id = '', 
                    user_id = 56, ),
                refund_id = '',
                send_email = '',
                send_note = '',
                send_pdf = '',
                send_status = 56,
                send_terms = '',
                status = 56,
                subscription = openapi_client.models.unibee/api/bean/subscription_simplify.unibee.api.bean.SubscriptionSimplify(
                    addon_data = '', 
                    amount = 56, 
                    billing_cycle_anchor = 56, 
                    cancel_at_period_end = 56, 
                    cancel_reason = '', 
                    country_code = '', 
                    create_time = 56, 
                    currency = '', 
                    current_period_end = 56, 
                    current_period_start = 56, 
                    dunning_time = 56, 
                    first_paid_time = 56, 
                    gas_payer = '', 
                    gateway_id = 56, 
                    gateway_item_data = '', 
                    gateway_status = '', 
                    id = 56, 
                    last_update_time = 56, 
                    latest_invoice_id = '', 
                    link = '', 
                    merchant_id = 56, 
                    metadata = {
                        'key' : ''
                        }, 
                    pending_update_id = '', 
                    plan_id = 56, 
                    quantity = 56, 
                    return_url = '', 
                    status = 56, 
                    subscription_id = '', 
                    task_time = '', 
                    tax_scale = 56, 
                    test_clock = 56, 
                    trial_end = 56, 
                    type = 56, 
                    user_id = 56, 
                    vat_number = '', ),
                subscription_amount = 56,
                subscription_amount_excluding_tax = 56,
                subscription_id = '',
                tax_amount = 56,
                tax_scale = 56,
                total_amount = 56,
                total_amount_excluding_tax = 56,
                unique_id = '',
                user_account = openapi_client.models.unibee/api/bean/user_account_simplify.unibee.api.bean.UserAccountSimplify(
                    address = '', 
                    avatar_url = '', 
                    billing_type = 56, 
                    birthday = '', 
                    company_name = '', 
                    country_code = '', 
                    country_name = '', 
                    create_time = 56, 
                    custom = '', 
                    email = '', 
                    external_user_id = '', 
                    facebook = '', 
                    first_name = '', 
                    gateway_id = '', 
                    gender = '', 
                    id = 56, 
                    is_risk = 56, 
                    is_special = 56, 
                    last_login_at = 56, 
                    last_name = '', 
                    linked_in = '', 
                    merchant_id = 56, 
                    mobile = '', 
                    other_social_info = '', 
                    payment_method = '', 
                    phone = '', 
                    profession = '', 
                    re_mark = '', 
                    recurring_amount = 56, 
                    school = '', 
                    status = 56, 
                    subscription_id = '', 
                    subscription_name = '', 
                    subscription_status = 56, 
                    telegram = '', 
                    tik_tok = '', 
                    time_zone = '', 
                    user_name = '', 
                    v_at_number = '', 
                    version = 56, 
                    we_chat = '', 
                    whats_app = '', ),
                user_id = 56
            )
        else:
            return UnibeeApiBeanDetailInvoiceDetail(
        )
        """

    def testUnibeeApiBeanDetailInvoiceDetail(self):
        """Test UnibeeApiBeanDetailInvoiceDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
