# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server

    The version of the OpenAPI document: buildtime:202404131246 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_webhook_resend_post200_response import MerchantWebhookResendPost200Response

class TestMerchantWebhookResendPost200Response(unittest.TestCase):
    """MerchantWebhookResendPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantWebhookResendPost200Response:
        """Test MerchantWebhookResendPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantWebhookResendPost200Response`
        """
        model = MerchantWebhookResendPost200Response()
        if include_optional:
            return MerchantWebhookResendPost200Response(
                code = 56,
                data = openapi_client.models._merchant_webhook_resend_post_200_response_data._merchant_webhook_resend_post_200_response_data(
                    send_result = True, ),
                message = '',
                redirect = '',
                request_id = ''
            )
        else:
            return MerchantWebhookResendPost200Response(
        )
        """

    def testMerchantWebhookResendPost200Response(self):
        """Test MerchantWebhookResendPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
