# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_payment_refund_list_get200_response_data import MerchantPaymentRefundListGet200ResponseData

class TestMerchantPaymentRefundListGet200ResponseData(unittest.TestCase):
    """MerchantPaymentRefundListGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantPaymentRefundListGet200ResponseData:
        """Test MerchantPaymentRefundListGet200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantPaymentRefundListGet200ResponseData`
        """
        model = MerchantPaymentRefundListGet200ResponseData()
        if include_optional:
            return MerchantPaymentRefundListGet200ResponseData(
                refund_details = [
                    openapi_client.models.unibee/internal/logic/gateway/ro/refund_detail_ro.unibee.internal.logic.gateway.ro.RefundDetailRo(
                        payment = openapi_client.models.unibee/internal/logic/gateway/ro/payment_simplify.unibee.internal.logic.gateway.ro.PaymentSimplify(
                            authorize_reason = '', 
                            authorize_status = 56, 
                            automatic = 56, 
                            balance_amount = 56, 
                            billing_reason = '', 
                            cancel_time = 56, 
                            country_code = '', 
                            create_time = 56, 
                            currency = '', 
                            external_payment_id = '', 
                            failure_reason = '', 
                            gateway_id = 56, 
                            gateway_payment_id = '', 
                            invoice_id = '', 
                            link = '', 
                            merchant_id = 56, 
                            paid_time = 56, 
                            payment_amount = 56, 
                            payment_id = '', 
                            refund_amount = 56, 
                            return_url = '', 
                            status = 56, 
                            subscription_id = '', 
                            total_amount = 56, 
                            user_id = 56, ), 
                        refund = openapi_client.models.unibee/internal/logic/gateway/ro/refund_simplify.unibee.internal.logic.gateway.ro.RefundSimplify(
                            country_code = '', 
                            create_time = 56, 
                            currency = '', 
                            external_refund_id = '', 
                            gateway_id = 56, 
                            gateway_refund_id = '', 
                            merchant_id = 56, 
                            payment_id = '', 
                            refund_amount = 56, 
                            refund_comment = '', 
                            refund_id = '', 
                            refund_time = 56, 
                            return_url = '', 
                            status = 56, 
                            subscription_id = '', 
                            user_id = 56, ), 
                        user = openapi_client.models.unibee/internal/logic/gateway/ro/user_account_simplify.unibee.internal.logic.gateway.ro.UserAccountSimplify(
                            address = '', 
                            create_time = 56, 
                            email = '', 
                            external_user_id = '', 
                            first_name = '', 
                            id = 56, 
                            last_name = '', 
                            merchant_id = 56, ), )
                    ]
            )
        else:
            return MerchantPaymentRefundListGet200ResponseData(
        )
        """

    def testMerchantPaymentRefundListGet200ResponseData(self):
        """Test MerchantPaymentRefundListGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
