# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server

    The version of the OpenAPI document: buildtime:202404131246 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_profile_new_api_key_res import UnibeeApiMerchantProfileNewApiKeyRes

class TestUnibeeApiMerchantProfileNewApiKeyRes(unittest.TestCase):
    """UnibeeApiMerchantProfileNewApiKeyRes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantProfileNewApiKeyRes:
        """Test UnibeeApiMerchantProfileNewApiKeyRes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantProfileNewApiKeyRes`
        """
        model = UnibeeApiMerchantProfileNewApiKeyRes()
        if include_optional:
            return UnibeeApiMerchantProfileNewApiKeyRes(
                api_key = ''
            )
        else:
            return UnibeeApiMerchantProfileNewApiKeyRes(
        )
        """

    def testUnibeeApiMerchantProfileNewApiKeyRes(self):
        """Test UnibeeApiMerchantProfileNewApiKeyRes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
