# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.session import Session


class TestSession(unittest.TestCase):
    """Session unit test stubs"""

    def setUp(self) -> None:
        self.api = Session()

    def tearDown(self) -> None:
        pass

    def test_session_new_session_post(self) -> None:
        """Test case for session_new_session_post

        New User Portal Session
        """
        pass


if __name__ == '__main__':
    unittest.main()
