# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.search import Search


class TestSearch(unittest.TestCase):
    """Search unit test stubs"""

    def setUp(self) -> None:
        self.api = Search()

    def tearDown(self) -> None:
        pass

    def test_search_key_search_get(self) -> None:
        """Test case for search_key_search_get

        Merchant Search
        """
        pass

    def test_search_key_search_post(self) -> None:
        """Test case for search_key_search_post

        Merchant Search
        """
        pass


if __name__ == '__main__':
    unittest.main()
