# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.gateway import Gateway


class TestGateway(unittest.TestCase):
    """Gateway unit test stubs"""

    def setUp(self) -> None:
        self.api = Gateway()

    def tearDown(self) -> None:
        pass

    def test_gateway_edit_post(self) -> None:
        """Test case for gateway_edit_post

        Gateway Webhook Edit
        """
        pass

    def test_gateway_list_get(self) -> None:
        """Test case for gateway_list_get

        Gateway List
        """
        pass

    def test_gateway_setup_post(self) -> None:
        """Test case for gateway_setup_post

        Gateway Setup
        """
        pass

    def test_gateway_setup_webhook_post(self) -> None:
        """Test case for gateway_setup_webhook_post

        Gateway Webhook Setup
        """
        pass


if __name__ == '__main__':
    unittest.main()
