# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server

    The version of the OpenAPI document: buildtime:202404131246 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_role_delete_req import UnibeeApiMerchantRoleDeleteReq

class TestUnibeeApiMerchantRoleDeleteReq(unittest.TestCase):
    """UnibeeApiMerchantRoleDeleteReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantRoleDeleteReq:
        """Test UnibeeApiMerchantRoleDeleteReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantRoleDeleteReq`
        """
        model = UnibeeApiMerchantRoleDeleteReq()
        if include_optional:
            return UnibeeApiMerchantRoleDeleteReq(
                role = ''
            )
        else:
            return UnibeeApiMerchantRoleDeleteReq(
                role = '',
        )
        """

    def testUnibeeApiMerchantRoleDeleteReq(self):
        """Test UnibeeApiMerchantRoleDeleteReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
