# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_plan_addons_binding_req import UnibeeApiMerchantPlanAddonsBindingReq

class TestUnibeeApiMerchantPlanAddonsBindingReq(unittest.TestCase):
    """UnibeeApiMerchantPlanAddonsBindingReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantPlanAddonsBindingReq:
        """Test UnibeeApiMerchantPlanAddonsBindingReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantPlanAddonsBindingReq`
        """
        model = UnibeeApiMerchantPlanAddonsBindingReq()
        if include_optional:
            return UnibeeApiMerchantPlanAddonsBindingReq(
                action = 56,
                addon_ids = [
                    56
                    ],
                plan_id = 56
            )
        else:
            return UnibeeApiMerchantPlanAddonsBindingReq(
                action = 56,
                addon_ids = [
                    56
                    ],
                plan_id = 56,
        )
        """

    def testUnibeeApiMerchantPlanAddonsBindingReq(self):
        """Test UnibeeApiMerchantPlanAddonsBindingReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
