# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.email import Email


class TestEmail(unittest.TestCase):
    """Email unit test stubs"""

    def setUp(self) -> None:
        self.api = Email()

    def tearDown(self) -> None:
        pass

    def test_email_gateway_setup_post(self) -> None:
        """Test case for email_gateway_setup_post

        Merchant Email Gateway Setup
        """
        pass


if __name__ == '__main__':
    unittest.main()
