# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_internal_logic_gateway_ro_user_account_simplify import UnibeeInternalLogicGatewayRoUserAccountSimplify

class TestUnibeeInternalLogicGatewayRoUserAccountSimplify(unittest.TestCase):
    """UnibeeInternalLogicGatewayRoUserAccountSimplify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeInternalLogicGatewayRoUserAccountSimplify:
        """Test UnibeeInternalLogicGatewayRoUserAccountSimplify
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeInternalLogicGatewayRoUserAccountSimplify`
        """
        model = UnibeeInternalLogicGatewayRoUserAccountSimplify()
        if include_optional:
            return UnibeeInternalLogicGatewayRoUserAccountSimplify(
                address = '',
                create_time = 56,
                email = '',
                external_user_id = '',
                first_name = '',
                id = 56,
                last_name = '',
                merchant_id = 56
            )
        else:
            return UnibeeInternalLogicGatewayRoUserAccountSimplify(
        )
        """

    def testUnibeeInternalLogicGatewayRoUserAccountSimplify(self):
        """Test UnibeeInternalLogicGatewayRoUserAccountSimplify"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
