# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server

    The version of the OpenAPI document: buildtime:202404131246 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_payment_method_new_req import UnibeeApiMerchantPaymentMethodNewReq

class TestUnibeeApiMerchantPaymentMethodNewReq(unittest.TestCase):
    """UnibeeApiMerchantPaymentMethodNewReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantPaymentMethodNewReq:
        """Test UnibeeApiMerchantPaymentMethodNewReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantPaymentMethodNewReq`
        """
        model = UnibeeApiMerchantPaymentMethodNewReq()
        if include_optional:
            return UnibeeApiMerchantPaymentMethodNewReq(
                currency = '',
                data = openapi_client.models.data.data(),
                gateway_id = 56,
                redirect_url = '',
                subscription_id = '',
                type = '',
                user_id = 56
            )
        else:
            return UnibeeApiMerchantPaymentMethodNewReq(
                currency = '',
                gateway_id = 56,
                user_id = 56,
        )
        """

    def testUnibeeApiMerchantPaymentMethodNewReq(self):
        """Test UnibeeApiMerchantPaymentMethodNewReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
