# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_gateway_setup_webhook_post200_response_data import MerchantGatewaySetupWebhookPost200ResponseData

class TestMerchantGatewaySetupWebhookPost200ResponseData(unittest.TestCase):
    """MerchantGatewaySetupWebhookPost200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantGatewaySetupWebhookPost200ResponseData:
        """Test MerchantGatewaySetupWebhookPost200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantGatewaySetupWebhookPost200ResponseData`
        """
        model = MerchantGatewaySetupWebhookPost200ResponseData()
        if include_optional:
            return MerchantGatewaySetupWebhookPost200ResponseData(
                gateway_webhook_url = ''
            )
        else:
            return MerchantGatewaySetupWebhookPost200ResponseData(
        )
        """

    def testMerchantGatewaySetupWebhookPost200ResponseData(self):
        """Test MerchantGatewaySetupWebhookPost200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
