# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_metric_delete_post200_response import MerchantMetricDeletePost200Response

class TestMerchantMetricDeletePost200Response(unittest.TestCase):
    """MerchantMetricDeletePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantMetricDeletePost200Response:
        """Test MerchantMetricDeletePost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantMetricDeletePost200Response`
        """
        model = MerchantMetricDeletePost200Response()
        if include_optional:
            return MerchantMetricDeletePost200Response(
                code = 56,
                data = openapi_client.models._merchant_metric_delete_post_200_response_data._merchant_metric_delete_post_200_response_data(
                    merchant_metric = openapi_client.models.unibee/internal/logic/gateway/ro/merchant_metric_vo.unibee.internal.logic.gateway.ro.MerchantMetricVo(
                        aggregation_property = '', 
                        aggregation_type = 56, 
                        code = '', 
                        create_time = 56, 
                        gmt_modify = 56, 
                        id = 56, 
                        merchant_id = 56, 
                        metric_description = '', 
                        metric_name = '', 
                        type = 56, ), ),
                message = '',
                redirect = '',
                request_id = ''
            )
        else:
            return MerchantMetricDeletePost200Response(
        )
        """

    def testMerchantMetricDeletePost200Response(self):
        """Test MerchantMetricDeletePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
