# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server

    The version of the OpenAPI document: buildtime:202404131246 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_payment_method_new_post200_response import MerchantPaymentMethodNewPost200Response

class TestMerchantPaymentMethodNewPost200Response(unittest.TestCase):
    """MerchantPaymentMethodNewPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantPaymentMethodNewPost200Response:
        """Test MerchantPaymentMethodNewPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantPaymentMethodNewPost200Response`
        """
        model = MerchantPaymentMethodNewPost200Response()
        if include_optional:
            return MerchantPaymentMethodNewPost200Response(
                code = 56,
                data = openapi_client.models._merchant_payment_method_new_post_200_response_data._merchant_payment_method_new_post_200_response_data(
                    method = openapi_client.models.unibee/api/bean/payment_method.unibee.api.bean.PaymentMethod(
                        data = openapi_client.models.data.data(), 
                        id = '', 
                        type = '', ), 
                    url = '', ),
                message = '',
                redirect = '',
                request_id = ''
            )
        else:
            return MerchantPaymentMethodNewPost200Response(
        )
        """

    def testMerchantPaymentMethodNewPost200Response(self):
        """Test MerchantPaymentMethodNewPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
