# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_internal_model_entity_oversea_pay_merchant_webhook_log import UnibeeInternalModelEntityOverseaPayMerchantWebhookLog

class TestUnibeeInternalModelEntityOverseaPayMerchantWebhookLog(unittest.TestCase):
    """UnibeeInternalModelEntityOverseaPayMerchantWebhookLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeInternalModelEntityOverseaPayMerchantWebhookLog:
        """Test UnibeeInternalModelEntityOverseaPayMerchantWebhookLog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeInternalModelEntityOverseaPayMerchantWebhookLog`
        """
        model = UnibeeInternalModelEntityOverseaPayMerchantWebhookLog()
        if include_optional:
            return UnibeeInternalModelEntityOverseaPayMerchantWebhookLog(
                body = '',
                create_time = 56,
                endpoint_id = 56,
                gmt_create = '',
                gmt_modify = '',
                id = 56,
                mamo = '',
                merchant_id = 56,
                reconsume_count = 56,
                request_id = '',
                response = '',
                webhook_event = '',
                webhook_url = ''
            )
        else:
            return UnibeeInternalModelEntityOverseaPayMerchantWebhookLog(
        )
        """

    def testUnibeeInternalModelEntityOverseaPayMerchantWebhookLog(self):
        """Test UnibeeInternalModelEntityOverseaPayMerchantWebhookLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
