# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth import Auth


class TestAuth(unittest.TestCase):
    """Auth unit test stubs"""

    def setUp(self) -> None:
        self.api = Auth()

    def tearDown(self) -> None:
        pass

    def test_auth_sso_login_otp_post(self) -> None:
        """Test case for auth_sso_login_otp_post

        Login OTP
        """
        pass

    def test_auth_sso_login_otp_verify_post(self) -> None:
        """Test case for auth_sso_login_otp_verify_post

        Merchant User OTP Login Verify
        """
        pass

    def test_auth_sso_login_post(self) -> None:
        """Test case for auth_sso_login_post

        Login
        """
        pass

    def test_auth_sso_password_forget_otp_post(self) -> None:
        """Test case for auth_sso_password_forget_otp_post

        Merchant Password Forget OTP
        """
        pass

    def test_auth_sso_password_forget_otp_verify_post(self) -> None:
        """Test case for auth_sso_password_forget_otp_verify_post

        Merchant Password Forget OTP Verify
        """
        pass

    def test_auth_sso_register_post(self) -> None:
        """Test case for auth_sso_register_post

        Merchant Register
        """
        pass

    def test_auth_sso_register_verify_post(self) -> None:
        """Test case for auth_sso_register_verify_post

        Merchant Register Verify
        """
        pass


if __name__ == '__main__':
    unittest.main()
