# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subscription_timeline import SubscriptionTimeline


class TestSubscriptionTimeline(unittest.TestCase):
    """SubscriptionTimeline unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionTimeline()

    def tearDown(self) -> None:
        pass

    def test_subscription_timeline_list_get(self) -> None:
        """Test case for subscription_timeline_list_get

        Merchant Subscription TimeLine List
        """
        pass

    def test_subscription_timeline_list_post(self) -> None:
        """Test case for subscription_timeline_list_post

        Merchant Subscription TimeLine List
        """
        pass


if __name__ == '__main__':
    unittest.main()
