# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.member import Member


class TestMember(unittest.TestCase):
    """Member unit test stubs"""

    def setUp(self) -> None:
        self.api = Member()

    def tearDown(self) -> None:
        pass

    def test_member_logout_post(self) -> None:
        """Test case for member_logout_post

        Merchant Member Logout
        """
        pass

    def test_member_password_reset_post(self) -> None:
        """Test case for member_password_reset_post

        Merchant Member Reset Password
        """
        pass

    def test_member_profile_get(self) -> None:
        """Test case for member_profile_get

        Get Merchant Member Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
