# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_bean_merchant_metric_simplify import UnibeeApiBeanMerchantMetricSimplify

class TestUnibeeApiBeanMerchantMetricSimplify(unittest.TestCase):
    """UnibeeApiBeanMerchantMetricSimplify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiBeanMerchantMetricSimplify:
        """Test UnibeeApiBeanMerchantMetricSimplify
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiBeanMerchantMetricSimplify`
        """
        model = UnibeeApiBeanMerchantMetricSimplify()
        if include_optional:
            return UnibeeApiBeanMerchantMetricSimplify(
                aggregation_property = '',
                aggregation_type = 56,
                code = '',
                create_time = 56,
                gmt_modify = 56,
                id = 56,
                merchant_id = 56,
                metric_description = '',
                metric_name = '',
                type = 56
            )
        else:
            return UnibeeApiBeanMerchantMetricSimplify(
        )
        """

    def testUnibeeApiBeanMerchantMetricSimplify(self):
        """Test UnibeeApiBeanMerchantMetricSimplify"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
