# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_plan_addons_binding_post200_response import MerchantPlanAddonsBindingPost200Response

class TestMerchantPlanAddonsBindingPost200Response(unittest.TestCase):
    """MerchantPlanAddonsBindingPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantPlanAddonsBindingPost200Response:
        """Test MerchantPlanAddonsBindingPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantPlanAddonsBindingPost200Response`
        """
        model = MerchantPlanAddonsBindingPost200Response()
        if include_optional:
            return MerchantPlanAddonsBindingPost200Response(
                code = 56,
                data = openapi_client.models._merchant_plan_addons_binding_post_200_response_data._merchant_plan_addons_binding_post_200_response_data(
                    plan = openapi_client.models.unibee/internal/logic/gateway/ro/plan_simplify.unibee.internal.logic.gateway.ro.PlanSimplify(
                        amount = 56, 
                        binding_addon_ids = '', 
                        create_time = 56, 
                        currency = '', 
                        description = '', 
                        extra_metric_data = '', 
                        home_url = '', 
                        id = 56, 
                        image_url = '', 
                        interval_count = 56, 
                        interval_unit = '', 
                        merchant_id = 56, 
                        plan_name = '', 
                        product_description = '', 
                        product_name = '', 
                        publish_status = 56, 
                        status = 56, 
                        tax_scale = 56, 
                        type = 56, ), ),
                message = '',
                redirect = '',
                request_id = ''
            )
        else:
            return MerchantPlanAddonsBindingPost200Response(
        )
        """

    def testMerchantPlanAddonsBindingPost200Response(self):
        """Test MerchantPlanAddonsBindingPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
