# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.profile import Profile


class TestProfile(unittest.TestCase):
    """Profile unit test stubs"""

    def setUp(self) -> None:
        self.api = Profile()

    def tearDown(self) -> None:
        pass

    def test_get_get(self) -> None:
        """Test case for get_get

        Get Merchant Info
        """
        pass

    def test_update_post(self) -> None:
        """Test case for update_post

        Update Merchant Info
        """
        pass


if __name__ == '__main__':
    unittest.main()
