# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.webhook import Webhook


class TestWebhook(unittest.TestCase):
    """Webhook unit test stubs"""

    def setUp(self) -> None:
        self.api = Webhook()

    def tearDown(self) -> None:
        pass

    def test_webhook_delete_endpoint_post(self) -> None:
        """Test case for webhook_delete_endpoint_post

        Merchant Delete Webhook Endpoint
        """
        pass

    def test_webhook_endpoint_list_get(self) -> None:
        """Test case for webhook_endpoint_list_get

        Merchant Webhook Endpoint list
        """
        pass

    def test_webhook_endpoint_log_list_get(self) -> None:
        """Test case for webhook_endpoint_log_list_get

        Merchant Webhook Endpoint Log list
        """
        pass

    def test_webhook_event_list_get(self) -> None:
        """Test case for webhook_event_list_get

        Webhook Event list
        """
        pass

    def test_webhook_new_endpoint_post(self) -> None:
        """Test case for webhook_new_endpoint_post

        Merchant New Webhook Endpoint
        """
        pass

    def test_webhook_update_endpoint_post(self) -> None:
        """Test case for webhook_update_endpoint_post

        Merchant Update Webhook Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
