# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_subscription_admin_note_ro import UnibeeApiMerchantSubscriptionAdminNoteRo

class TestUnibeeApiMerchantSubscriptionAdminNoteRo(unittest.TestCase):
    """UnibeeApiMerchantSubscriptionAdminNoteRo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantSubscriptionAdminNoteRo:
        """Test UnibeeApiMerchantSubscriptionAdminNoteRo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantSubscriptionAdminNoteRo`
        """
        model = UnibeeApiMerchantSubscriptionAdminNoteRo()
        if include_optional:
            return UnibeeApiMerchantSubscriptionAdminNoteRo(
                create_time = 56,
                email = '',
                first_name = '',
                id = 56,
                last_name = '',
                mobile = '',
                note = '',
                subscription_id = '',
                user_name = ''
            )
        else:
            return UnibeeApiMerchantSubscriptionAdminNoteRo(
        )
        """

    def testUnibeeApiMerchantSubscriptionAdminNoteRo(self):
        """Test UnibeeApiMerchantSubscriptionAdminNoteRo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
