# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_bean_invoice_simplify import UnibeeApiBeanInvoiceSimplify

class TestUnibeeApiBeanInvoiceSimplify(unittest.TestCase):
    """UnibeeApiBeanInvoiceSimplify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiBeanInvoiceSimplify:
        """Test UnibeeApiBeanInvoiceSimplify
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiBeanInvoiceSimplify`
        """
        model = UnibeeApiBeanInvoiceSimplify()
        if include_optional:
            return UnibeeApiBeanInvoiceSimplify(
                biz_type = 56,
                currency = '',
                id = 56,
                invoice_id = '',
                invoice_name = '',
                lines = [
                    openapi_client.models.unibee/api/bean/invoice_item_simplify.unibee.api.bean.InvoiceItemSimplify(
                        amount = 56, 
                        amount_excluding_tax = 56, 
                        currency = '', 
                        description = '', 
                        period_end = 56, 
                        period_start = 56, 
                        proration = True, 
                        quantity = 56, 
                        tax = 56, 
                        tax_scale = 56, 
                        unit_amount_excluding_tax = 56, )
                    ],
                link = '',
                payment_id = '',
                payment_link = '',
                period_end = 56,
                period_start = 56,
                proration_date = 56,
                proration_scale = 56,
                refund_id = '',
                status = 56,
                subscription_amount = 56,
                subscription_amount_excluding_tax = 56,
                tax_amount = 56,
                tax_scale = 56,
                total_amount = 56,
                total_amount_excluding_tax = 56
            )
        else:
            return UnibeeApiBeanInvoiceSimplify(
        )
        """

    def testUnibeeApiBeanInvoiceSimplify(self):
        """Test UnibeeApiBeanInvoiceSimplify"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
