# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.balance import Balance


class TestBalance(unittest.TestCase):
    """Balance unit test stubs"""

    def setUp(self) -> None:
        self.api = Balance()

    def tearDown(self) -> None:
        pass

    def test_balance_merchant_balance_query_get(self) -> None:
        """Test case for balance_merchant_balance_query_get

        Query Merchant Gateway Balance
        """
        pass

    def test_balance_merchant_balance_query_post(self) -> None:
        """Test case for balance_merchant_balance_query_post

        Query Merchant Gateway Balance
        """
        pass

    def test_balance_user_balance_query_get(self) -> None:
        """Test case for balance_user_balance_query_get

        Query User Balance
        """
        pass

    def test_balance_user_balance_query_post(self) -> None:
        """Test case for balance_user_balance_query_post

        Query User Balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
