# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_profile_country_config_list_res import UnibeeApiMerchantProfileCountryConfigListRes

class TestUnibeeApiMerchantProfileCountryConfigListRes(unittest.TestCase):
    """UnibeeApiMerchantProfileCountryConfigListRes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantProfileCountryConfigListRes:
        """Test UnibeeApiMerchantProfileCountryConfigListRes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantProfileCountryConfigListRes`
        """
        model = UnibeeApiMerchantProfileCountryConfigListRes()
        if include_optional:
            return UnibeeApiMerchantProfileCountryConfigListRes(
                configs = [
                    openapi_client.models.unibee/api/bean/merchant_country_config_simplify.unibee.api.bean.MerchantCountryConfigSimplify(
                        country_code = '', 
                        merchant_id = 56, 
                        name = '', )
                    ]
            )
        else:
            return UnibeeApiMerchantProfileCountryConfigListRes(
        )
        """

    def testUnibeeApiMerchantProfileCountryConfigListRes(self):
        """Test UnibeeApiMerchantProfileCountryConfigListRes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
