# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.email_template import EmailTemplate


class TestEmailTemplate(unittest.TestCase):
    """EmailTemplate unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailTemplate()

    def tearDown(self) -> None:
        pass

    def test_email_template_activate_post(self) -> None:
        """Test case for email_template_activate_post

        Merchant Email Template Activate
        """
        pass

    def test_email_template_deactivate_post(self) -> None:
        """Test case for email_template_deactivate_post

        Merchant Email Template Deactivate
        """
        pass

    def test_email_template_list_get(self) -> None:
        """Test case for email_template_list_get

        Merchant Email Template List
        """
        pass

    def test_email_template_set_default_post(self) -> None:
        """Test case for email_template_set_default_post

        Merchant Email Template Set Default
        """
        pass

    def test_email_template_update_post(self) -> None:
        """Test case for email_template_update_post

        Merchant Email Template Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
