# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_metric_user_metric_get200_response_data import MerchantMetricUserMetricGet200ResponseData

class TestMerchantMetricUserMetricGet200ResponseData(unittest.TestCase):
    """MerchantMetricUserMetricGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantMetricUserMetricGet200ResponseData:
        """Test MerchantMetricUserMetricGet200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantMetricUserMetricGet200ResponseData`
        """
        model = MerchantMetricUserMetricGet200ResponseData()
        if include_optional:
            return MerchantMetricUserMetricGet200ResponseData(
                user_metric = openapi_client.models.unibee/internal/logic/gateway/ro/user_metric.unibee.internal.logic.gateway.ro.UserMetric(
                    addons = [
                        openapi_client.models.unibee/internal/logic/gateway/ro/plan_addon_vo.unibee.internal.logic.gateway.ro.PlanAddonVo(
                            addon_plan = openapi_client.models.unibee/internal/logic/gateway/ro/plan_simplify.unibee.internal.logic.gateway.ro.PlanSimplify(
                                amount = 56, 
                                binding_addon_ids = '', 
                                create_time = 56, 
                                currency = '', 
                                description = '', 
                                extra_metric_data = '', 
                                home_url = '', 
                                id = 56, 
                                image_url = '', 
                                interval_count = 56, 
                                interval_unit = '', 
                                merchant_id = 56, 
                                plan_name = '', 
                                product_description = '', 
                                product_name = '', 
                                publish_status = 56, 
                                status = 56, 
                                tax_scale = 56, 
                                type = 56, ), 
                            quantity = 56, )
                        ], 
                    is_paid = True, 
                    plan = openapi_client.models.unibee/internal/logic/gateway/ro/plan_simplify.unibee.internal.logic.gateway.ro.PlanSimplify(
                        amount = 56, 
                        binding_addon_ids = '', 
                        create_time = 56, 
                        currency = '', 
                        description = '', 
                        extra_metric_data = '', 
                        home_url = '', 
                        id = 56, 
                        image_url = '', 
                        interval_count = 56, 
                        interval_unit = '', 
                        merchant_id = 56, 
                        plan_name = '', 
                        product_description = '', 
                        product_name = '', 
                        publish_status = 56, 
                        status = 56, 
                        tax_scale = 56, 
                        type = 56, ), 
                    subscription = openapi_client.models.unibee/internal/logic/gateway/ro/subscription_simplify.unibee.internal.logic.gateway.ro.SubscriptionSimplify(
                        addon_data = '', 
                        amount = 56, 
                        billing_cycle_anchor = 56, 
                        cancel_at_period_end = 56, 
                        cancel_reason = '', 
                        country_code = '', 
                        create_time = 56, 
                        currency = '', 
                        current_period_end = 56, 
                        current_period_start = 56, 
                        dunning_time = 56, 
                        first_paid_time = 56, 
                        gateway_id = 56, 
                        gateway_item_data = '', 
                        gateway_status = '', 
                        id = 56, 
                        last_update_time = 56, 
                        latest_invoice_id = '', 
                        link = '', 
                        merchant_id = 56, 
                        pending_update_id = '', 
                        plan_id = 56, 
                        quantity = 56, 
                        return_url = '', 
                        status = 56, 
                        subscription_id = '', 
                        task_time = '', 
                        tax_scale = 56, 
                        test_clock = 56, 
                        trial_end = 56, 
                        type = 56, 
                        user_id = 56, 
                        vat_number = '', ), 
                    user = openapi_client.models.unibee/internal/logic/gateway/ro/user_account_simplify.unibee.internal.logic.gateway.ro.UserAccountSimplify(
                        address = '', 
                        create_time = 56, 
                        email = '', 
                        external_user_id = '', 
                        first_name = '', 
                        id = 56, 
                        last_name = '', 
                        merchant_id = 56, ), 
                    user_merchant_metric_stats = [
                        openapi_client.models.unibee/internal/logic/gateway/ro/user_merchant_metric_stat.unibee.internal.logic.gateway.ro.UserMerchantMetricStat(
                            current_use_value = 56, 
                            metric_limit = openapi_client.models.unibee/internal/logic/gateway/ro/metric_limit_vo.unibee.internal.logic.gateway.ro.MetricLimitVo(
                                merchant_id = 56, 
                                metric_id = 56, 
                                plan_limits = [
                                    openapi_client.models.unibee/internal/logic/gateway/ro/merchant_metric_plan_limit_vo.unibee.internal.logic.gateway.ro.MerchantMetricPlanLimitVo(
                                        create_time = 56, 
                                        gmt_modify = 56, 
                                        id = 56, 
                                        merchant_id = 56, 
                                        merchant_metric_vo = openapi_client.models.unibee/internal/logic/gateway/ro/merchant_metric_vo.unibee.internal.logic.gateway.ro.MerchantMetricVo(
                                            aggregation_property = '', 
                                            aggregation_type = 56, 
                                            code = '', 
                                            create_time = 56, 
                                            gmt_modify = 56, 
                                            id = 56, 
                                            merchant_id = 56, 
                                            metric_description = '', 
                                            metric_name = '', 
                                            type = 56, ), 
                                        metric_id = 56, 
                                        metric_limit = 56, 
                                        plan_id = 56, )
                                    ], 
                                total_limit = 56, 
                                user_id = 56, 
                                aggregation_property = '', 
                                aggregation_type = 56, 
                                code = '', 
                                metric_name = '', 
                                type = 56, ), )
                        ], )
            )
        else:
            return MerchantMetricUserMetricGet200ResponseData(
        )
        """

    def testMerchantMetricUserMetricGet200ResponseData(self):
        """Test MerchantMetricUserMetricGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
