# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_user_update_req import UnibeeApiMerchantUserUpdateReq

class TestUnibeeApiMerchantUserUpdateReq(unittest.TestCase):
    """UnibeeApiMerchantUserUpdateReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantUserUpdateReq:
        """Test UnibeeApiMerchantUserUpdateReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantUserUpdateReq`
        """
        model = UnibeeApiMerchantUserUpdateReq()
        if include_optional:
            return UnibeeApiMerchantUserUpdateReq(
                linked_in = '',
                address = '',
                company_name = '',
                country_code = '',
                country_name = '',
                email = '',
                facebook = '',
                first_name = '',
                last_name = '',
                other_social_info = '',
                payment_method = '',
                phone = '',
                telegram = '',
                tiktok = '',
                user_id = 56,
                v_at_number = '',
                we_chat = '',
                whats_app = ''
            )
        else:
            return UnibeeApiMerchantUserUpdateReq(
                address = '',
                country_code = '',
                country_name = '',
                email = '',
                first_name = '',
                last_name = '',
                user_id = 56,
        )
        """

    def testUnibeeApiMerchantUserUpdateReq(self):
        """Test UnibeeApiMerchantUserUpdateReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
