# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_merchant_balance_detail_query_res import UnibeeApiMerchantBalanceDetailQueryRes

class TestUnibeeApiMerchantBalanceDetailQueryRes(unittest.TestCase):
    """UnibeeApiMerchantBalanceDetailQueryRes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiMerchantBalanceDetailQueryRes:
        """Test UnibeeApiMerchantBalanceDetailQueryRes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiMerchantBalanceDetailQueryRes`
        """
        model = UnibeeApiMerchantBalanceDetailQueryRes()
        if include_optional:
            return UnibeeApiMerchantBalanceDetailQueryRes(
                available = [
                    openapi_client.models.unibee/internal/logic/gateway/ro/gateway_balance.unibee.internal.logic.gateway.ro.GatewayBalance(
                        amount = 56, 
                        currency = '', )
                    ],
                connect_reserved = [
                    openapi_client.models.unibee/internal/logic/gateway/ro/gateway_balance.unibee.internal.logic.gateway.ro.GatewayBalance(
                        amount = 56, 
                        currency = '', )
                    ],
                pending = [
                    openapi_client.models.unibee/internal/logic/gateway/ro/gateway_balance.unibee.internal.logic.gateway.ro.GatewayBalance(
                        amount = 56, 
                        currency = '', )
                    ]
            )
        else:
            return UnibeeApiMerchantBalanceDetailQueryRes(
        )
        """

    def testUnibeeApiMerchantBalanceDetailQueryRes(self):
        """Test UnibeeApiMerchantBalanceDetailQueryRes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
