# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.file import File


class TestFile(unittest.TestCase):
    """File unit test stubs"""

    def setUp(self) -> None:
        self.api = File()

    def tearDown(self) -> None:
        pass

    def test_oss_file_post(self) -> None:
        """Test case for oss_file_post

        Upload File
        """
        pass


if __name__ == '__main__':
    unittest.main()
