# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_bean_bulk_metric_limit_plan_binding_param import UnibeeApiBeanBulkMetricLimitPlanBindingParam

class TestUnibeeApiBeanBulkMetricLimitPlanBindingParam(unittest.TestCase):
    """UnibeeApiBeanBulkMetricLimitPlanBindingParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiBeanBulkMetricLimitPlanBindingParam:
        """Test UnibeeApiBeanBulkMetricLimitPlanBindingParam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiBeanBulkMetricLimitPlanBindingParam`
        """
        model = UnibeeApiBeanBulkMetricLimitPlanBindingParam()
        if include_optional:
            return UnibeeApiBeanBulkMetricLimitPlanBindingParam(
                metric_id = 56,
                metric_limit = 56
            )
        else:
            return UnibeeApiBeanBulkMetricLimitPlanBindingParam(
                metric_id = 56,
                metric_limit = 56,
        )
        """

    def testUnibeeApiBeanBulkMetricLimitPlanBindingParam(self):
        """Test UnibeeApiBeanBulkMetricLimitPlanBindingParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
