# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_subscription_config_get200_response_data import MerchantSubscriptionConfigGet200ResponseData

class TestMerchantSubscriptionConfigGet200ResponseData(unittest.TestCase):
    """MerchantSubscriptionConfigGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantSubscriptionConfigGet200ResponseData:
        """Test MerchantSubscriptionConfigGet200ResponseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantSubscriptionConfigGet200ResponseData`
        """
        model = MerchantSubscriptionConfigGet200ResponseData()
        if include_optional:
            return MerchantSubscriptionConfigGet200ResponseData(
                config = openapi_client.models.unibee/api/bean/subscription_config.unibee.api.bean.SubscriptionConfig(
                    downgrade_effect_immediately = True, 
                    incomplete_expire_time = 56, 
                    invoice_email = True, 
                    upgrade_proration = True, )
            )
        else:
            return MerchantSubscriptionConfigGet200ResponseData(
        )
        """

    def testMerchantSubscriptionConfigGet200ResponseData(self):
        """Test MerchantSubscriptionConfigGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
