# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_internal_model_entity_oversea_pay_payment import UnibeeInternalModelEntityOverseaPayPayment

class TestUnibeeInternalModelEntityOverseaPayPayment(unittest.TestCase):
    """UnibeeInternalModelEntityOverseaPayPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeInternalModelEntityOverseaPayPayment:
        """Test UnibeeInternalModelEntityOverseaPayPayment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeInternalModelEntityOverseaPayPayment`
        """
        model = UnibeeInternalModelEntityOverseaPayPayment()
        if include_optional:
            return UnibeeInternalModelEntityOverseaPayPayment(
                additional_data = '',
                app_id = '',
                authorize_reason = '',
                authorize_status = 56,
                automatic = 56,
                balance_amount = 56,
                balance_end = 56,
                balance_start = 56,
                billing_reason = '',
                biz_type = 56,
                cancel_time = 56,
                capture_delay_hours = 56,
                code = '',
                company_id = 56,
                country_code = '',
                create_time = 56,
                currency = '',
                external_payment_id = '',
                failure_reason = '',
                gateway_edition = '',
                gateway_id = 56,
                gateway_payment_id = '',
                gateway_payment_intent_id = '',
                gateway_payment_method = '',
                gmt_create = '',
                gmt_modify = '',
                hide_payment_methods = '',
                id = 56,
                invoice_data = '',
                invoice_id = '',
                link = '',
                merchant_id = 56,
                open_api_id = 56,
                paid_time = 56,
                payment_amount = 56,
                payment_data = '',
                payment_id = '',
                refund_amount = 56,
                return_url = '',
                status = 56,
                subscription_id = '',
                terminal_ip = '',
                token = '',
                total_amount = 56,
                unique_id = '',
                user_id = 56,
                verify = ''
            )
        else:
            return UnibeeInternalModelEntityOverseaPayPayment(
        )
        """

    def testUnibeeInternalModelEntityOverseaPayPayment(self):
        """Test UnibeeInternalModelEntityOverseaPayPayment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
