# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.vat import Vat


class TestVat(unittest.TestCase):
    """Vat unit test stubs"""

    def setUp(self) -> None:
        self.api = Vat()

    def tearDown(self) -> None:
        pass

    def test_vat_country_list_get(self) -> None:
        """Test case for vat_country_list_get

        Vat Country List
        """
        pass

    def test_vat_country_list_post(self) -> None:
        """Test case for vat_country_list_post

        Vat Country List
        """
        pass

    def test_vat_setup_gateway_post(self) -> None:
        """Test case for vat_setup_gateway_post

        Vat Gateway Setup
        """
        pass


if __name__ == '__main__':
    unittest.main()
