# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_api_bean_gateway_simplify import UnibeeApiBeanGatewaySimplify

class TestUnibeeApiBeanGatewaySimplify(unittest.TestCase):
    """UnibeeApiBeanGatewaySimplify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeApiBeanGatewaySimplify:
        """Test UnibeeApiBeanGatewaySimplify
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeApiBeanGatewaySimplify`
        """
        model = UnibeeApiBeanGatewaySimplify()
        if include_optional:
            return UnibeeApiBeanGatewaySimplify(
                gateway_id = 56,
                gateway_logo = '',
                gateway_name = '',
                gateway_type = 56
            )
        else:
            return UnibeeApiBeanGatewaySimplify(
        )
        """

    def testUnibeeApiBeanGatewaySimplify(self):
        """Test UnibeeApiBeanGatewaySimplify"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
