# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unibee_internal_model_entity_oversea_pay_subscription import UnibeeInternalModelEntityOverseaPaySubscription

class TestUnibeeInternalModelEntityOverseaPaySubscription(unittest.TestCase):
    """UnibeeInternalModelEntityOverseaPaySubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnibeeInternalModelEntityOverseaPaySubscription:
        """Test UnibeeInternalModelEntityOverseaPaySubscription
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnibeeInternalModelEntityOverseaPaySubscription`
        """
        model = UnibeeInternalModelEntityOverseaPaySubscription()
        if include_optional:
            return UnibeeInternalModelEntityOverseaPaySubscription(
                addon_data = '',
                amount = 56,
                billing_cycle_anchor = 56,
                cancel_at_period_end = 56,
                cancel_reason = '',
                country_code = '',
                create_time = 56,
                currency = '',
                current_period_end = 56,
                current_period_end_time = '',
                current_period_start = 56,
                current_period_start_time = '',
                customer_email = '',
                customer_name = '',
                data = '',
                dunning_time = 56,
                first_paid_time = 56,
                gateway_default_payment_method = '',
                gateway_id = 56,
                gateway_item_data = '',
                gateway_latest_invoice_id = '',
                gateway_status = '',
                gateway_subscription_id = '',
                gmt_create = '',
                gmt_modify = '',
                id = 56,
                is_deleted = 56,
                last_update_time = 56,
                latest_invoice_id = '',
                link = '',
                merchant_id = 56,
                pending_update_id = '',
                plan_id = 56,
                quantity = 56,
                response_data = '',
                return_url = '',
                status = 56,
                subscription_id = '',
                task_time = '',
                tax_scale = 56,
                test_clock = 56,
                trial_end = 56,
                type = 56,
                user_id = 56,
                vat_number = '',
                vat_verify_data = ''
            )
        else:
            return UnibeeInternalModelEntityOverseaPaySubscription(
        )
        """

    def testUnibeeInternalModelEntityOverseaPaySubscription(self):
        """Test UnibeeInternalModelEntityOverseaPaySubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
