# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server

    The version of the OpenAPI document: buildtime:202404131246 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.unibee_api_bean_plan_simplify import UnibeeApiBeanPlanSimplify
from typing import Optional, Set
from typing_extensions import Self

class UnibeeApiBeanInvoiceItemSimplify(BaseModel):
    """
    UnibeeApiBeanInvoiceItemSimplify
    """ # noqa: E501
    amount: Optional[StrictInt] = None
    amount_excluding_tax: Optional[StrictInt] = Field(default=None, alias="amountExcludingTax")
    currency: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    period_end: Optional[StrictInt] = Field(default=None, alias="periodEnd")
    period_start: Optional[StrictInt] = Field(default=None, alias="periodStart")
    plan: Optional[UnibeeApiBeanPlanSimplify] = None
    proration: Optional[StrictBool] = None
    quantity: Optional[StrictInt] = None
    tax: Optional[StrictInt] = None
    tax_percentage: Optional[StrictInt] = Field(default=None, description="Tax Percentage，1000 = 10%", alias="taxPercentage")
    unit_amount_excluding_tax: Optional[StrictInt] = Field(default=None, alias="unitAmountExcludingTax")
    __properties: ClassVar[List[str]] = ["amount", "amountExcludingTax", "currency", "description", "periodEnd", "periodStart", "plan", "proration", "quantity", "tax", "taxPercentage", "unitAmountExcludingTax"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeApiBeanInvoiceItemSimplify from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of plan
        if self.plan:
            _dict['plan'] = self.plan.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeApiBeanInvoiceItemSimplify from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "amountExcludingTax": obj.get("amountExcludingTax"),
            "currency": obj.get("currency"),
            "description": obj.get("description"),
            "periodEnd": obj.get("periodEnd"),
            "periodStart": obj.get("periodStart"),
            "plan": UnibeeApiBeanPlanSimplify.from_dict(obj["plan"]) if obj.get("plan") is not None else None,
            "proration": obj.get("proration"),
            "quantity": obj.get("quantity"),
            "tax": obj.get("tax"),
            "taxPercentage": obj.get("taxPercentage"),
            "unitAmountExcludingTax": obj.get("unitAmountExcludingTax")
        })
        return _obj


