# coding: utf-8

"""
    OpenAPI UniBee

    This is UniBee api server, For this sample, you can use the api key `EUXAgwv3Vcr1PFWt2SgBumMHXn3ImBqM` to test the authorization filters

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UnibeeInternalModelEntityOverseaPaySubscriptionPendingUpdate(BaseModel):
    """
    UnibeeInternalModelEntityOverseaPaySubscriptionPendingUpdate
    """ # noqa: E501
    addon_data: Optional[StrictStr] = Field(default=None, description="plan addon data (json) of this period", alias="addonData")
    amount: Optional[StrictInt] = Field(default=None, description="amount of this period, cent")
    create_time: Optional[StrictInt] = Field(default=None, description="create utc time", alias="createTime")
    currency: Optional[StrictStr] = Field(default=None, description="currency of this period")
    data: Optional[StrictStr] = None
    effect_immediate: Optional[StrictInt] = Field(default=None, description="effect immediate，0-no，1-yes", alias="effectImmediate")
    effect_time: Optional[StrictInt] = Field(default=None, description="effect_immediate=0, effect time, utc_time", alias="effectTime")
    gateway_id: Optional[StrictInt] = Field(default=None, description="gateway_id", alias="gatewayId")
    gateway_status: Optional[StrictStr] = Field(default=None, description="gateway status", alias="gatewayStatus")
    gmt_create: Optional[StrictStr] = Field(default=None, description="create time", alias="gmtCreate")
    gmt_modify: Optional[StrictStr] = Field(default=None, description="update time", alias="gmtModify")
    id: Optional[StrictInt] = Field(default=None, description="id")
    invoice_id: Optional[StrictStr] = Field(default=None, description="gateway update payment id assosiate to this update, use payment.paymentId", alias="invoiceId")
    is_deleted: Optional[StrictInt] = Field(default=None, description="0-UnDeleted，1-Deleted", alias="isDeleted")
    link: Optional[StrictStr] = Field(default=None, description="payment link")
    merchant_id: Optional[StrictInt] = Field(default=None, description="merchant id", alias="merchantId")
    merchant_member_id: Optional[StrictInt] = Field(default=None, description="merchant_user_id", alias="merchantMemberId")
    name: Optional[StrictStr] = Field(default=None, description="name")
    note: Optional[StrictStr] = Field(default=None, description="note")
    paid: Optional[StrictInt] = Field(default=None, description="paid，0-no，1-yes")
    plan_id: Optional[StrictInt] = Field(default=None, description="the plan id of this period", alias="planId")
    proration_amount: Optional[StrictInt] = Field(default=None, description="proration amount of this pending update , cent", alias="prorationAmount")
    proration_date: Optional[StrictInt] = Field(default=None, description="merchant_user_id", alias="prorationDate")
    quantity: Optional[StrictInt] = Field(default=None, description="quantity of this period")
    response_data: Optional[StrictStr] = Field(default=None, alias="responseData")
    status: Optional[StrictInt] = Field(default=None, description="status，0-Init | 1-Create｜2-Finished｜3-Cancelled")
    subscription_id: Optional[StrictStr] = Field(default=None, description="subscription id", alias="subscriptionId")
    update_addon_data: Optional[StrictStr] = Field(default=None, description="plan addon data (json) after update", alias="updateAddonData")
    update_amount: Optional[StrictInt] = Field(default=None, description="the amount after update", alias="updateAmount")
    update_currency: Optional[StrictStr] = Field(default=None, description="the currency after update", alias="updateCurrency")
    update_plan_id: Optional[StrictInt] = Field(default=None, description="the plan id after update", alias="updatePlanId")
    update_quantity: Optional[StrictInt] = Field(default=None, description="quantity after update", alias="updateQuantity")
    update_subscription_id: Optional[StrictStr] = Field(default=None, description="pending update unique id", alias="updateSubscriptionId")
    user_id: Optional[StrictInt] = Field(default=None, description="userId", alias="userId")
    __properties: ClassVar[List[str]] = ["addonData", "amount", "createTime", "currency", "data", "effectImmediate", "effectTime", "gatewayId", "gatewayStatus", "gmtCreate", "gmtModify", "id", "invoiceId", "isDeleted", "link", "merchantId", "merchantMemberId", "name", "note", "paid", "planId", "prorationAmount", "prorationDate", "quantity", "responseData", "status", "subscriptionId", "updateAddonData", "updateAmount", "updateCurrency", "updatePlanId", "updateQuantity", "updateSubscriptionId", "userId"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnibeeInternalModelEntityOverseaPaySubscriptionPendingUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnibeeInternalModelEntityOverseaPaySubscriptionPendingUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "addonData": obj.get("addonData"),
            "amount": obj.get("amount"),
            "createTime": obj.get("createTime"),
            "currency": obj.get("currency"),
            "data": obj.get("data"),
            "effectImmediate": obj.get("effectImmediate"),
            "effectTime": obj.get("effectTime"),
            "gatewayId": obj.get("gatewayId"),
            "gatewayStatus": obj.get("gatewayStatus"),
            "gmtCreate": obj.get("gmtCreate"),
            "gmtModify": obj.get("gmtModify"),
            "id": obj.get("id"),
            "invoiceId": obj.get("invoiceId"),
            "isDeleted": obj.get("isDeleted"),
            "link": obj.get("link"),
            "merchantId": obj.get("merchantId"),
            "merchantMemberId": obj.get("merchantMemberId"),
            "name": obj.get("name"),
            "note": obj.get("note"),
            "paid": obj.get("paid"),
            "planId": obj.get("planId"),
            "prorationAmount": obj.get("prorationAmount"),
            "prorationDate": obj.get("prorationDate"),
            "quantity": obj.get("quantity"),
            "responseData": obj.get("responseData"),
            "status": obj.get("status"),
            "subscriptionId": obj.get("subscriptionId"),
            "updateAddonData": obj.get("updateAddonData"),
            "updateAmount": obj.get("updateAmount"),
            "updateCurrency": obj.get("updateCurrency"),
            "updatePlanId": obj.get("updatePlanId"),
            "updateQuantity": obj.get("updateQuantity"),
            "updateSubscriptionId": obj.get("updateSubscriptionId"),
            "userId": obj.get("userId")
        })
        return _obj


